### ISSUE TITLE
Auto Approve Open Shift Requests - Wrong action in IF-branch

### ISSUE THREAD

**Issue by ad2012** [OfficeDev/Microsoft-Teams-Shifts-Power-Automate-Templates#1]
Hi there, hi @raulfernandes ,
the "Auto Approve Open Shift Requests" template utilizes the wrong Shift-Action "Shift: Approve an **Offer** Shift requests" instead of "Shift: Approve an **Open** Shift requests".
This will cause an "Shifts:_Approve_an_Offer_Shift_request" error.

`{
  "error": {
    "code": "Forbidden",
    "message": "{\"error\":{\"code\":\"Forbidden\",\"message\":\"Sie können nur auf Schichtangebots- und -tauschanträge antworten.\",\"details\":[],\"innererror\":{\"code\":\"ShiftRequestNotAvailable\"}}}",
    "innerError": {
      "request-id": "93d3b673-672f-4682-afff-xxxxxxxxxxxx",
      "date": "2020-06-02T17:28:30"
    }
  }
}`

This can be seen in the screenshot from readme, too:
![image](https://user-images.githubusercontent.com/2690733/83552663-6884a180-a50a-11ea-9550-b8cb93d0d77e.png)

**Comment by raulfernandes** [comment]
Thanks for reporting this @ad2012. I've pushed updates to fix the issue and also updated the flows to use the new "Shifts" connector. 

FYI, the new connector now supports filtering to only fetch "pending" requests that need to be responded to:
![image](https://user-images.githubusercontent.com/1371970/87569467-04620b00-c67c-11ea-9230-f0deeccbd94e.png)
