### ISSUE TITLE
Response capped at 100 items

### ISSUE THREAD

**Issue by buildbod** [OfficeDev/Microsoft-Teams-Shifts-Power-Automate-Templates#2]
The Shifts list actions will only return the first 100 items. It is possible to increase this by manipulating the Top value but this is hit and miss as $count and paging is not supported and so you have to guess and hope you do not hit another threshold e.g. threshold on the upper limit of the response

**Comment by raulfernandes** [comment]
@buildbod Apologies for the slow response, pagination should now be supported. It can be enabled from under settings:

![image](https://user-images.githubusercontent.com/1371970/90920926-02d3e300-e39e-11ea-8e53-bf7f141274a3.png)

![image](https://user-images.githubusercontent.com/1371970/90920998-24cd6580-e39e-11ea-9381-6bceba728399.png)

**Comment by buildbod** [comment]
Thank you for the update and pagination certainly helps!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
