### ISSUE TITLE
Open Shift Request Approving in Reverse Sequence

### ISSUE THREAD

**Issue by 4computing** [OfficeDev/Microsoft-Teams-Shifts-Power-Automate-Templates#5]
When more than 1 request from different users for the same open shift occurs in-between runs the Approve an Open Shift Request action approves the newest request and denies the older requests. Essentially a Last In First Out method.  Seems that it should be First In First Out so the first request gets approved.  

Is there a way to filter the list of open shift requests and make it approve in the order the request come in from first to last?

**Comment by raulfernandes** [comment]
@4computing Thanks for calling out this scenario, I'm not sure if it's currently possible. But we're working on an approach to make a FIFO based approval process work.

**Comment by raulfernandes** [comment]
@4computing We have now added triggers to notify you when a new request is created/updated/deleted. You could use this trigger to detect as soon as a request is created, and approve it immediately in a FIFO manner. 

We're in the process of adding templates into Power Automate to help with setting this up.

**Comment by raulfernandes** [comment]
![image](https://user-images.githubusercontent.com/1371970/94613238-2ae61a00-0259-11eb-8d6f-bc05a6b98ca6.png)
