### ISSUE TITLE
Errors running the Approve Open Shift Requests

### ISSUE THREAD

**Issue by vxac** [OfficeDev/Microsoft-Teams-Shifts-Power-Automate-Templates#6]
I get an error running the open shifts request flow, but the flow still performs the actions successfully. I get a "Forbidden" notice on the approval step, and the following error:

`{"error":{"code":"Forbidden","message":"This shift request is not in a state to be `approved.","details":[],"innererror":{"code":"ShiftRequestsCannotBeActedUpon"}}}`

`{
  "error": {
    "code": "Forbidden",
    "message": "{\"error\":{\"code\":\"Forbidden\",\"message\":\"This shift request is not in a state to be approved.\",\"details\":[],\"innererror\":{\"code\":\"ShiftRequestsCannotBeActedUpon\"}}}",
    "innerError": {
      "date": "2020-08-21T11:10:41",
      "request-id": "23d3a28b-24ab-4df7-8771-f339a9714a72"
    }
  }
}`

**Comment by raulfernandes** [comment]
Thanks for the report, we're working on a fix for it.

**Comment by raulfernandes** [comment]
This should be fixed now
