### ISSUE TITLE
Error importing ShareMyShiftsasiCalendarFeed.zip

### ISSUE THREAD

**Issue by angelcakesgit** [OfficeDev/Microsoft-Teams-Shifts-Power-Automate-Templates#7]
I get an error when importing the ShareMyShiftsasiCalendarFeed.zip file:

"The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.
Error code 80048060."

https://support.microsoft.com/en-us/help/4456506/the-solution-file-is-invalid-error-occurs-in-dynamics-365

How do I get the template to import? Thanks!

**Comment by raulfernandes** [comment]
@angelcakesgit Refer to these instructions here: https://github.com/OfficeDev/Microsoft-Teams-Shifts-Power-Automate-Templates#Using-the-templates

**Comment by raulfernandes** [comment]
Templates are now available officially: https://flow.microsoft.com/en-us/connectors/shared_shifts/shifts-for-microsoft-teams/
