### ISSUE TITLE
Conditions only return 'Yes' if [assignedTo] is set to 'recipient' rather than 'manager'

### ISSUE THREAD

**Issue by Spiraculous** [OfficeDev/Microsoft-Teams-Shifts-Power-Automate-Templates#8]
Hi.  I have created and manage a team to test Shifts and have set up groups, Open Shifts and added test users.  I'd like to use Flows to auto approve Open Shifts but the Auto Approve Offer Shift Requests and Auto Convert Shift to Open Shift Flows fail at the 'Offer Shift Request Is Assigned To: Is Equal To: 'manager' stage unless I change 'manager' to 'recipient'.  The shifts are being offered to and approved by me as owner and manager of the team.

Here's a section of an Open Shift object offered to me returned to the flow at the 'Condition: Shift being offered directly to manager' stage:
 
    "createdDateTime": "2020-08-27T16:15:41.769Z",
    "lastModifiedDateTime": "2020-08-27T16:15:41.769Z",
    "assignedTo": "recipient",
    "state": "pending",
    "senderDateTime": "2020-08-27T16:15:41.769Z",
    "senderMessage": "",
    

I'm new to this - what am I missing here? Is it an O365/Teams configuration issue?  It seems to me that if I leave the flow property as 'recipient' any Open Shift offered to any other group member will be returned to the pool.

**Comment by raulfernandes** [comment]
@Spiraculous You're right. That's a typo in the template. We'll fix it soon, thanks for calling it out.

**Comment by Spiraculous** [comment]
Thanks very much for the prompt reply.  What does that condition actually test for?  Is it just to check that managers aren't offering shifts to each other?

**Comment by raulfernandes** [comment]
@Spiraculous Sorry, I missed your comment. 
Typically (swap/offer) requests go through 2 stages of approval:
1. Assigned to "recipient": Request is sent to the recipient of the shift for approval
2. Assigned to "manager": After the recipient of the request approves, it goes to the manager for approval

With open shifts, this check is actually not necessary.

**Comment by raulfernandes** [comment]
The official Shifts templates are now available: https://flow.microsoft.com/en-us/connectors/shared_shifts/shifts-for-microsoft-teams/
